#ifndef PARAMS_H
#define PARAMS_H

#define PARALLEL_HOTSTUFF
#define MAX_NUM_NODES 7
#define MAX_NUM_SIGNATURES 5
#define MAX_NUM_TRANSACTIONS 100
#define PAYLOAD_SIZE 0
#define MAX_BLOCKS_IN_VIEW 1

#endif
