#ifndef PARAMS_H
#define PARAMS_H

#define PARALLEL_HOTSTUFF
#define MAX_NUM_NODES 25
#define MAX_NUM_SIGNATURES 17
#define MAX_NUM_TRANSACTIONS 400
#define PAYLOAD_SIZE 0
#define MAX_BLOCKS_IN_VIEW 16

#endif
