#ifndef PARAMS_H
#define PARAMS_H

#define PARALLEL_HOTSTUFF
#define MAX_NUM_NODES 13
#define MAX_NUM_SIGNATURES 9
#define MAX_NUM_TRANSACTIONS 400
#define PAYLOAD_SIZE 256
#define MAX_BLOCKS_IN_VIEW 8

#endif
